# Generated by Django 4.0.5 on 2022-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateField()),
                ('accountNumber', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
