# Generated by Django 4.0.5 on 2022-06-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dateRegistered', models.DateField()),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reksadana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unitPrice', models.CharField(max_length=50)),
                ('unitNumber', models.IntegerField()),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalboss.user')),
            ],
        ),
    ]
